package Ranaka.ranaka.common.enums;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    CREATE_DRAFT,
    UPDATE_DRAFT,
    SUBMIT_REQUEST,
    RECOMMEND_REQUEST,
    APPROVE_REQUEST,
    AUTHORIZE_REQUEST,
    REJECT_REQUEST,
    RETURN_REQUEST,
    CREATE_COMMENT,
    UPLOAD_ATTACHMENT,
    CREATE_USER,
    UPDATE_USER,
    DEACTIVATE_USER,
    SETTINGS_CHANGED
}
